Week 3/ChefsDishes/Models/Chef.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
// using Microsoft.EntityFrameworkCore;
namespace ChefsDishes.Models;

public class Chef 
{
    [Key]
    public int ChefId {get;set;}

    [Required]
    [MinLength(2)]
    public string FirstName {get;set;}

    [Required]
    [MinLength(2)]
    public string LastName {get;set;}

    [Required(ErrorMessage = "Date of Birth is required")]
    [DataType(DataType.Date)]
    [DateValidation(ErrorMessage = "Date of Birth must be in the past")]
    public DateTime DOB {get;set;}

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public List<Dish> AllDishes {get;set;} = new List<Dish>();
}

public class DateValidation : ValidationAttribute
{
    public override bool IsValid(object value)
    {
        if (value is DateTime DOB)
        {
            return DOB < DateTime.Today;
        }
        return false;
    }
}

Week 3/ChefsDishes/Models/Dish.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
// using Microsoft.EntityFrameworkCore;
namespace ChefsDishes.Models;

public class Dish 
{ 
    [Key]
    public int DishId {get;set;}

    [Required]
    public string Name {get;set;}

    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Must have calories")]
    public int Calories {get;set;}

    [Required]
    [Range(1, 5)]
    public int Tastiness {get;set;}

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public int ChefId {get;set;}

    public Chef? Creator {get;set;}
}

Week 3/ChefsDishes/Models/ErrorViewModel.cs
namespace ChefsDishes.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Week 3/ChefsDishes/Models/MyContext.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
namespace ChefsDishes.Models;

public class MyContext : DbContext
{  
    // This line will always be here. It is what constructs our context upon initialization  
    public MyContext(DbContextOptions options) : base(options) { }    
    // We need to create a new DbSet<Model> for every model in our project that is making a table
    // The name of our table in our database will be based on the name we provide here
    // This is where we provide a plural version of our model to fit table naming standards    
    public DbSet<Dish> Dishes { get; set; }
    public DbSet<Chef> Chefs { get; set; }
}

Week 3/ChefsDishes/Controllers/ChefController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using ChefsDishes.Models;
using System.Reflection.Metadata.Ecma335;

namespace ChefsDishes.Controllers;

public class ChefController : Controller
{
    private readonly ILogger<ChefController> _logger;

    private MyContext _context;

    public ChefController(ILogger<ChefController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

    // **** LANDING PAGE ******************* not anymore sike 
    // [HttpGet("")]
    // public IActionResult Index()
    // {
    //     List<Dish> AllDishes = _context.Dishes.ToList();
    //     return View();
    // }

    // [HttpGet("")]
    // public IActionResult AllChefs()
    // {
    //     return View();
    // }


    // ***** CREATE ***************
    [HttpGet("chefs/new")]
    public IActionResult NewChef()
    {
        return View();
    }

    [HttpPost("chefs/create")]
    public IActionResult CreateChef(Chef newChef)
    {
        if (ModelState.IsValid)
        {
            _context.Add(newChef);
            _context.SaveChanges();
            return RedirectToAction("AllChefs");
        }
        else
        {
            // if invalid redirect to the form again
            return View("NewChef");
        }
    }

    // ****** GET ALL **************
    // coincidentally this is also our landing page
    [HttpGet("")]
    public IActionResult AllChefs()
    {
        List<Chef> chefs = _context.Chefs.ToList();
        return View(chefs);
    }

    // ******


}

Week 3/ChefsDishes/Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using ChefsDishes.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ChefsDishes.Controllers;

public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;

    private MyContext _context;

    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

    // ****** NEW DISHES **************

    [HttpGet("dishes/new")]
    public IActionResult NewDish()
    {
        List<Chef> chefs = _context.Chefs.ToList();
        ViewBag.ChefsList = new SelectList(chefs, "ChefId", "FirstName");
        return View();
    }

    [HttpPost("dishes/create")]
    public IActionResult CreateDish (Dish newDish)
    {
        if(ModelState.IsValid)
        {
            int chosenChefId = newDish.ChefId;
            // grabs the ChefId from the dish
            newDish.Creator = _context.Chefs.FirstOrDefault(c => c.ChefId == chosenChefId);
            // grabs the entirety of the Chef object and assigns it to the Creator, as defined in the model
            _context.Add(newDish);
            _context.SaveChanges();
            return RedirectToAction("AllDishes");
        } else {
            // if invalid redirect to the form again
            return View("NewDish");
        }
    }

    // ******** ALL DISHES ************
    [HttpGet("dishes/all")]
    public IActionResult AllDishes() =>
        // grabs the list of all the dishes and created a variable to send through to the alldishes page
        // ViewBag.Context = _context;
        // this makes absolutely no sense why I had to use ViewBag to send context through to make the ChefId thing work
        View((List<Dish>)_context.Dishes.Include(d => d.Creator).ToList());
}

Week 3/ChefsDishes/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ChefsDishes.Models;

namespace ChefsDishes.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    // public IActionResult Index()
    // {
    //     return View();
    // }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Week 3/ChefsDishes/Views/Chef/AllChefs.cshtml
@model List<Chef>
    @* need to inject an instance of mycontext in order to use it on this page *@
@inject MyContext _context
@using Microsoft.EntityFrameworkCore; 
    @{
    ViewData["Title"] = "All Chefs";
}

<h1>Check out our roster of chefs!</h1>
<hr>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Number of Dishes</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Chef chef in Model)
        {
            <tr>
                <td>@chef.FirstName @chef.LastName</td>
                <td>@{
                    int age = DateTime.Today.Year - chef.DOB.Year;
                    if (chef.DOB > DateTime.Today.AddYears(-age)) 
                        {
                            age--;
                        }
                    @age
                }
                </td>
                <td>@{
                    int num = _context.Chefs.Include(c => c.AllDishes).Single(c => c.ChefId == chef.ChefId).AllDishes.Count; 
                    @num
                }
                </td>
            </tr>
        }
    </tbody>
</table>

Week 3/ChefsDishes/Views/Chef/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Week 3/ChefsDishes/Views/Chef/NewChef.cshtml
@model Chef

<h1>Add a New Chef!</h1>
<hr>
<form asp-action="CreateChef" asp-controller="Chef" method="POST">
    <div class="m-3">
        <label asp-for="FirstName">First Name: </label>
        <input asp-for="FirstName" />
        <span asp-validation-for="FirstName"></span>
    </div>
    <div class="m-3">
        <label asp-for="LastName">Last Name: </label>
        <input asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>
    <div class="m-3">
        <label asp-for="DOB">Date of Birth: </label>
        <input asp-for="DOB" type="date"/>
        <span asp-validation-for="DOB"></span>
    </div>
    <button type="submit">Add Chef</button>
</form>

Week 3/ChefsDishes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChefsDishes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChefsDishes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chef" asp-action="NewChef">Add A Chef</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="NewDish">Add A Dish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="AllDishes">Dishes!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chef" asp-action="AllChefs">Chefs!</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ChefsDishes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>